name: PartyGames
main: me.sisko.partygames.Main
version: 1.3
api-version: 1.16
author: Captain_Sisko
depend: [Vault, LuckPerms, PlaceholderAPI]
softdepend: [FastAsyncWorldEdit]
commands:
  play:
    description: test command
    usage:
        /play <game>
